name: Keep Codespace Alive

on:
  schedule:
    # Runs every 25 minutes
    - cron: "*/25 * * * *"

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Send Keep-Alive Request
        run: |
          curl -m 5 https://potential-space-yodel-v6r9vx5x7x99fwj4q.github.dev/ || echo "Codespace not reachable"


