name: Keep Codespace Alive

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Start Codespace
        run: |
          echo "Pinging Codespace to keep it alive..."
          curl -s -o /dev/null https://potential-space-yodel-v6r9vx5x7x99fwj4q.github.dev/
